POSTGRES_USER_NAME="postgres"
POSTGRES_USER_PASSWORD="postgres"
POSTGRES_DB_NAME="postgres"
POSTGRES_DB_HOST="127.0.0.1"
POSTGRES_PORT=5433
POCO_SERVER_PORT=80
JWT_SECRET_WORD="0123456789ABCDEF0123456789ABCDEF"